name: Create Git Tag
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag to be used (e.g., all)"
        required: true
        default: "all"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Authenticate with PAT
        run: git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

      - name: Create & Push Tag
        run: |
          git tag ${{ github.event.inputs.tag_name }}
          git push origin ${{ github.event.inputs.tag_name }}
