name: Manual-Action-Workflow
on:
  workflow_dispatch

jobs:
  run-automation-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install CodeceptJs + Playwright
        run:  npx playwright install

      - name: Run tests SkinX BackOffice
        run: NODE_ENV=dev npx codeceptjs run "tests/login/*.ts"
        continue-on-error: true

      - name: Send To Teams
        run: npm run sendToTeams