name: SkinX - Run Test
on:
  repository_dispatch:
    types:
      - run-tests

jobs:
  check-pr-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3