name: Run Automation on Tag
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag to be used (e.g., all)"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - login
          - apptInfo

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install CodeceptJs + Playwright
        run:  npx playwright install

      - name: Extract Tag Name
        run: echo "TAG_NAME=${{ github.event.inputs.tag_name }}"

      - name: Run tests with tag filter
        run: NODE_ENV=dev npx codeceptjs run "tests/login/*.ts" --grep ${{ github.event.inputs.tag_name }}
        continue-on-error: true

      - name: Send To Teams
        run: npm run sendToTeams