name: SkinX - Run Test
on:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - main

jobs:
  check-pr-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3