name: SkinX - Run Test
on:
  repository_dispatch:
    types:
      - run-*

jobs:
  run-tag-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Debug Event Payload
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Event Type: ${{ github.event.action }}"
          echo "Payload: ${{ toJson(github.event.client_payload) }}"