name: "Run Tests on Tag Update"

# on:
#   repository_dispatch:
#     types:
#       - run-tests

on:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Display Tag Received
      run: echo "Running tests for TAG: ${{ github.event.client_payload.tag }}"