name: Run Automation on Tag
on:
  push:
    tags:
      - "**"  # Trigger เมื่อมี Tag อะไรก็ได้ถูกสร้าง

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install CodeceptJs + Playwright
        run:  npx playwright install

      - name: Extract Tag Name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Run tests with tag filter
        run: NODE_ENV=dev npx codeceptjs run "tests/login/*.ts" --grep $TAG_NAME
        continue-on-error: true

      - name: Send To Teams
        run: npm run sendToTeams