name: SkinX - Run Test
on:
  push:
    branches:
      - main

jobs:
  run-tag-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Display Tag Received
        run: echo "Running tests for TAG: ${{ github.event.client_payload.tag }}"